// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJKrBAfDCewpiTwz2Qhp8b7I60UcKLfuA',
    appId: '1:609189185473:web:2604f9dd8c182343f0d140',
    messagingSenderId: '609189185473',
    projectId: 'kidilingo',
    authDomain: 'kidilingo.firebaseapp.com',
    storageBucket: 'kidilingo.firebasestorage.app',
    measurementId: 'G-S5RVM1EQZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV151p5PJOgoWMJc6DcNy16MoVj8l-Rpo',
    appId: '1:609189185473:android:8e72e322fb9822b3f0d140',
    messagingSenderId: '609189185473',
    projectId: 'kidilingo',
    storageBucket: 'kidilingo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLIQYtk8wfd83zNI6zhw8ZwV0UxViyXcQ',
    appId: '1:609189185473:ios:811e4a14e26827c9f0d140',
    messagingSenderId: '609189185473',
    projectId: 'kidilingo',
    storageBucket: 'kidilingo.firebasestorage.app',
    iosBundleId: 'com.example.kiddylingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLIQYtk8wfd83zNI6zhw8ZwV0UxViyXcQ',
    appId: '1:609189185473:ios:811e4a14e26827c9f0d140',
    messagingSenderId: '609189185473',
    projectId: 'kidilingo',
    storageBucket: 'kidilingo.firebasestorage.app',
    iosBundleId: 'com.example.kiddylingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJKrBAfDCewpiTwz2Qhp8b7I60UcKLfuA',
    appId: '1:609189185473:web:f392e4dd61c466c2f0d140',
    messagingSenderId: '609189185473',
    projectId: 'kidilingo',
    authDomain: 'kidilingo.firebaseapp.com',
    storageBucket: 'kidilingo.firebasestorage.app',
    measurementId: 'G-DSR5NW1YY1',
  );
}
